default_platform(:android)

platform :android do
  desc "Build and upload to Google Play"
  lane :deploy do
    build_android_app(
      task: "bundle",
      project_dir: "android/",
      print_command: true,
      properties: {
        "android.injected.signing.store.file" => ENV["KEYSTORE_PATH"],
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEYSTORE_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEYSTORE_KEY_PASSWORD"],
      }
    )

    upload_to_play_store(
      track: "internal",
      release_status: "completed",
      aab: lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]
    )
  end

  desc "Build release APK"
  lane :build_apk do
    build_android_app(
      task: "assemble",
      build_type: "Release",
      project_dir: "android/",
      print_command: true,
      properties: {
        "android.injected.signing.store.file" => ENV["KEYSTORE_PATH"],
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEYSTORE_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEYSTORE_KEY_PASSWORD"],
      }
    )
  end

  desc "Build release AAB"
  lane :build_aab do
    build_android_app(
      task: "bundle",
      project_dir: "android/",
      print_command: true,
      properties: {
        "android.injected.signing.store.file" => ENV["KEYSTORE_PATH"],
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEYSTORE_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEYSTORE_KEY_PASSWORD"],
      }
    )
  end
end
